version: 2
updates:
  # Check for npm package updates
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'edmolima'
    labels:
      - 'dependencies'
      - 'npm'
    commit-message:
      prefix: 'chore(deps):'
      prefix-development: 'chore(deps-dev):'
      include: 'scope'
    allow:
      - dependency-type: 'all'
    ignore:
      # Add packages to ignore if needed
      # - dependency-name: 'package-name'

  # Check for GitHub Actions updates
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5
    reviewers:
      - 'edmolima'
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'ci(actions):'
      include: 'scope'
